opemapi : "3.0.0"
info: 
    title: Shopping API
    version: "1.0"
paths:
    /products:
      description: The products catalog
      get: 
        summary: Search for products
        description: |
          search for products in catalog using
          free query parameter.
        parameter: [...]
        response: 
              "200":
               description: |
                   Products matching free query parameter
              content:
                   application/json :
                     schema:
                       type: array
                       description: Array of Products
                       items:
                         type: object
                         description: A product
                         required: 
                           - reference
                           - name
                           - price
                           - supplier
                         properties:
                           reference:
                            description: Unique ID Identifying a product
                            type: string
                           name:
                            type: string
                           supplier:
                             type: object
                             description: Product's supplier
                             required:
                              - reference
                              - name
                             properties:
                               reference: 
                                 type: string
                               name:
                                 type: string                        
        parameters: 
          - name: free-query
            description: |
              A product's name, reference, or 
              partial description
            in: query
            required: false
            schema:
              type: string 
      post: 
        summary: Add products
        description: |
          Add product to catalog
        response: "200":
          description : |
            product addded to the catalog